
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/eui/eui.js",
	"libs/modules/res/res.js",
	"libs/modules/tween/tween.js",
	"libs/modules/socket/socket.js",
	"libs/modules/dragonBones/dragonBones.js",
	"libs/modules/protobuf/protobuf.js",
	"libs/modules/async/async.js",
	"libs/modules/md5/md5.js",
	"libs/modules/clipbord/clipbord.js",
	"libs/modules/game/game.js",
	"bin-debug/core/PDKSeat.js",
	"bin-debug/alienlib/page/Navigator.js",
	"bin-debug/game/seat/PDKDDZSeat.js",
	"bin-debug/core/PDKServer.js",
	"bin-debug/alienlib/scene/SceneBase.js",
	"bin-debug/alienlib/support/EventManager.js",
	"bin-debug/alienlib/support/Native.js",
	"bin-debug/alienlib/support/PDKSoundManager.js",
	"bin-debug/alienlib/tools/Encrypt.js",
	"bin-debug/core/PDKCardGroup.js",
	"bin-debug/views/pages/PDKPageChannelBase.js",
	"bin-debug/alienlib/scene/SceneManager.js",
	"bin-debug/core/PDKService.js",
	"bin-debug/alienlib/popup/PDKPanelBase.js",
	"bin-debug/game/seat/PDKSideSeat.js",
	"bin-debug/model/PDKDataStorage.js",
	"bin-debug/model/PDKLanguagePack.js",
	"bin-debug/views/components/dragon/PDKBaseDragon.js",
	"bin-debug/alienlib/animation/IAnimation.js",
	"bin-debug/views/components/PDKGoodsItem.js",
	"bin-debug/alienlib/support/StageProxy.js",
	"bin-debug/alienlib/support/TickerManager.js",
	"bin-debug/alienlib/support/Vector2D.js",
	"bin-debug/alienlib/tools/Ajax.js",
	"bin-debug/alienlib/popup/PopupEffect.js",
	"bin-debug/alienlib/tools/HashMap.js",
	"bin-debug/alienlib/tools/MathUtils.js",
	"bin-debug/alienlib/tools/ObjectPool.js",
	"bin-debug/alienlib/tools/PDKBase64.js",
	"bin-debug/alienlib/tools/PDKUtils.js",
	"bin-debug/alienlib/tools/StringUtils.js",
	"bin-debug/alienlib/tools/TimeUtils.js",
	"bin-debug/alienlib/tools/TweenWatcher.js",
	"bin-debug/alienlib/ui/DropDown.js",
	"bin-debug/alienlib/ui/FadeSwitch.js",
	"bin-debug/alienlib/ui/Image.js",
	"bin-debug/alienlib/ui/PageProgressBar.js",
	"bin-debug/alienlib/ui/ScrollImage.js",
	"bin-debug/alienlib/ui/ScrollNavigator.js",
	"bin-debug/alienlib/ui/ViewStack.js",
	"bin-debug/core/PDKCard.js",
	"bin-debug/core/PDKCardBody.js",
	"bin-debug/alienlib/popup/PopUpManager.js",
	"bin-debug/core/PDKEnviroment.js",
	"bin-debug/core/PDKLogUtil.js",
	"bin-debug/core/PDKMainLogic.js",
	"bin-debug/core/PDKProtoIDs.js",
	"bin-debug/core/PDKReportor.js",
	"bin-debug/PDKDefines.js",
	"bin-debug/alienlib/scene/SceneEffect.js",
	"bin-debug/alienlib/animation/MovieClip.js",
	"bin-debug/core/PDKUtils.js",
	"bin-debug/game/PDKCardsHint.js",
	"bin-debug/game/PDKCardsType.js",
	"bin-debug/game/PDKDDZCardGroup.js",
	"bin-debug/game/PDKDDZServer.js",
	"bin-debug/game/PDKGameSoundManager.js",
	"bin-debug/game/PDKGoodsManager.js",
	"bin-debug/game/PDKObjectPoolInit.js",
	"bin-debug/game/PDKOtherGameManager.js",
	"bin-debug/game/PDKShareImageManager.js",
	"bin-debug/alienlib/support/Dispatcher.js",
	"bin-debug/game/seat/PDKLeftSeat.js",
	"bin-debug/game/seat/PDKMySeat.js",
	"bin-debug/game/seat/PDKRightSeat.js",
	"bin-debug/alienlib/animation/Wave.js",
	"bin-debug/game/service/PDKBagService.js",
	"bin-debug/game/service/PDKCountDownService.js",
	"bin-debug/game/service/PDKExchangeService.js",
	"bin-debug/game/service/PDKInviteService.js",
	"bin-debug/game/service/PDKLoginService.js",
	"bin-debug/game/service/PDKMailService.js",
	"bin-debug/game/service/PDKMatchService.js",
	"bin-debug/game/service/PDKMsgInfoService.js",
	"bin-debug/game/service/PDKPersonalGameHistory.js",
	"bin-debug/game/service/PDKRechargeService.js",
	"bin-debug/game/service/PDKWebService.js",
	"bin-debug/model/PDKBrowData.js",
	"bin-debug/alienlib/support/localStorage.js",
	"bin-debug/model/PDKDebugHelper.js",
	"bin-debug/model/PDKErrorConfig.js",
	"bin-debug/model/PDKEventNames.js",
	"bin-debug/model/PDKGameConfig.js",
	"bin-debug/model/PDKGameData.js",
	"bin-debug/model/PDKLanguage.js",
	"bin-debug/RunFastMain.js",
	"bin-debug/model/PDKResNames.js",
	"bin-debug/model/PDKSceneNames.js",
	"bin-debug/model/PDKUserData.js",
	"bin-debug/model/PDKUserInfoData.js",
	"bin-debug/model/PDKWxHelper.js",
	"bin-debug/ui_extend/PDKNormalButton.js",
	"bin-debug/ui_extend/PDKStateButton.js",
	"bin-debug/views/PDKAssetAdapter.js",
	"bin-debug/views/PDKThemeAdapter.js",
	"bin-debug/views/components/PDKActListItem.js",
	"bin-debug/views/components/PDKAvatar.js",
	"bin-debug/views/components/PDKButtonBar.js",
	"bin-debug/views/components/PDKButtonDoTaskSkin.js",
	"bin-debug/views/components/PDKCDClock.js",
	"bin-debug/views/components/PDKCDProgressBar.js",
	"bin-debug/views/components/PDKChatBubble.js",
	"bin-debug/views/components/PDKChatList.js",
	"bin-debug/views/components/PDKExchangeShowInfo.js",
	"bin-debug/views/components/PDKFeiHistoryItem.js",
	"bin-debug/views/components/PDKFlyGold.js",
	"bin-debug/views/components/PDKGCardsGold.js",
	"bin-debug/views/components/PDKGold.js",
	"bin-debug/views/components/PDKGoldRainEffectLayer.js",
	"bin-debug/views/scenes/ScenePDKPlay.js",
	"bin-debug/views/components/PDKHornTalkItem.js",
	"bin-debug/views/components/PDKInviteListItem.js",
	"bin-debug/views/components/PDKLoading.js",
	"bin-debug/views/components/PDKLoadingProcess.js",
	"bin-debug/views/components/PDKMarqueeText.js",
	"bin-debug/views/components/PDKMasterCards.js",
	"bin-debug/views/components/PDKPage.js",
	"bin-debug/views/components/PDKQProgressBar.js",
	"bin-debug/views/components/PDKRedPacketProcess.js",
	"bin-debug/views/components/PDKRobot.js",
	"bin-debug/views/components/PDKShopItem.js",
	"bin-debug/views/components/PDKToast.js",
	"bin-debug/views/components/PDKUserInfoView.js",
	"bin-debug/views/components/dayTask/PDKDayTaskItemInfo.js",
	"bin-debug/alienlib/support/PDKAdvanceMethod.js",
	"bin-debug/views/components/dragon/PDKDragonGameFeiJi.js",
	"bin-debug/views/components/dragon/PDKDragonGameLianDui.js",
	"bin-debug/views/components/dragon/PDKDragonGameSanDaiEr.js",
	"bin-debug/views/components/dragon/PDKDragonGameSanDaiYi.js",
	"bin-debug/views/components/dragon/PDKDragonGameShunZi.js",
	"bin-debug/views/components/dragon/PDKDragonGameSiDaiEr.js",
	"bin-debug/views/components/dragon/PDKDragonGameZhaDan.js",
	"bin-debug/views/components/dragon/PDKDragonHongBao.js",
	"bin-debug/views/components/dragon/PDKDragonHongBaoWarn.js",
	"bin-debug/views/components/dragon/PDKDragonJingDeng.js",
	"bin-debug/views/components/dragon/PDKDragonManager.js",
	"bin-debug/views/components/dragon/PDKDragonMatch9Rule.js",
	"bin-debug/views/components/dragon/PDKDragonSign.js",
	"bin-debug/views/components/dragon/PDKDragonSignBtn.js",
	"bin-debug/views/components/item_renderers/PDKIRButton.js",
	"bin-debug/views/components/item_renderers/PDKIRContainer.js",
	"bin-debug/views/components/item_renderers/PDKIRUpDownIcon.js",
	"bin-debug/views/components/personal/PDKCreateTable.js",
	"bin-debug/views/components/personal/PDKCreateTableInfo.js",
	"bin-debug/views/components/personal/PDKHistoryItem.js",
	"bin-debug/views/components/personal/PDKHistoryRecord.js",
	"bin-debug/views/components/personal/PDKImgToast.js",
	"bin-debug/views/components/personal/PDKImgWordBtn.js",
	"bin-debug/views/components/personal/PDKJoinTable.js",
	"bin-debug/views/components/personal/PDKPersonalDetail.js",
	"bin-debug/views/components/personal/PDKPersonalGame.js",
	"bin-debug/views/components/personal/PDKPInfItem.js",
	"bin-debug/views/components/personal/PDKTableInfo.js",
	"bin-debug/views/components/redRank/PDKRedRank.js",
	"bin-debug/views/components/redRank/PDKRedRankInfo.js",
	"bin-debug/alienlib/animation/Fade.js",
	"bin-debug/views/pages/PDKPageChannels.js",
	"bin-debug/views/pages/PDKPageMatchChannel.js",
	"bin-debug/views/pages/PDKPageNormalChannel.js",
	"bin-debug/views/panels/PDKPanelAct.js",
	"bin-debug/views/panels/PDKPanelActAndNotice.js",
	"bin-debug/views/panels/PDKPanelAlert.js",
	"bin-debug/views/panels/PDKPanelAlert2.js",
	"bin-debug/views/panels/PDKPanelAlert3.js",
	"bin-debug/views/panels/PDKPanelBeforeMatch.js",
	"bin-debug/views/panels/PDKPanelBindPhone.js",
	"bin-debug/views/panels/PDKPanelBuyRecorder.js",
	"bin-debug/views/panels/PDKPanelDayBuy.js",
	"bin-debug/views/panels/PDKPanelDayTask.js",
	"bin-debug/views/panels/PDKPanelDelegate.js",
	"bin-debug/views/panels/PDKPanelDownApp.js",
	"bin-debug/views/panels/PDKPanelExchange2.js",
	"bin-debug/views/panels/PDKPanelExchange3.js",
	"bin-debug/views/panels/PDKPanelFeiEx.js",
	"bin-debug/views/panels/PDKPanelFirstRechargeNew.js",
	"bin-debug/views/panels/PDKPanelFollowCourse.js",
	"bin-debug/views/panels/PDKPanelFreshManReward.js",
	"bin-debug/views/panels/PDKPanelFRGetRew.js",
	"bin-debug/views/panels/PDKPanelFristRecharge.js",
	"bin-debug/views/panels/PDKPanelGetItems.js",
	"bin-debug/views/panels/PDKPanelGetRed.js",
	"bin-debug/views/panels/PDKPanelHornTalk.js",
	"bin-debug/views/panels/PDKPanelInviteList.js",
	"bin-debug/views/panels/PDKPanelLogin.js",
	"bin-debug/views/panels/PDKPanelMail.js",
	"bin-debug/views/panels/PDKPanelMailDetails.js",
	"bin-debug/views/panels/PDKPanelMatch9GetRew.js",
	"bin-debug/views/panels/PDKPanelMatch9Info.js",
	"bin-debug/views/panels/PDKPanelMatchCountDown.js",
	"bin-debug/views/panels/PDKPanelMatchIntro.js",
	"bin-debug/views/panels/PDKPanelMatchNotice.js",
	"bin-debug/views/panels/PDKPanelMatchResult.js",
	"bin-debug/views/panels/PDKPanelMatchRevive.js",
	"bin-debug/views/panels/PDKPanelMatchSignUp.js",
	"bin-debug/views/panels/PDKPanelMatchWaiting.js",
	"bin-debug/views/panels/PDKPanelMatchWaitingInner.js",
	"bin-debug/views/panels/PDKPanelModifyNickname.js",
	"bin-debug/views/panels/PDKPanelNormalResult.js",
	"bin-debug/views/panels/PDKPanelNotice.js",
	"bin-debug/views/panels/PDKPanelPhoneLogin.js",
	"bin-debug/views/panels/PDKPanelPlayerInfo.js",
	"bin-debug/views/panels/PDKPanelProfile.js",
	"bin-debug/views/panels/PDKPanelRechargeTips.js",
	"bin-debug/views/panels/PDKPanelReviveBag.js",
	"bin-debug/views/panels/PDKPanelRuleTip.js",
	"bin-debug/views/panels/PDKPanelSelectAvatar.js",
	"bin-debug/views/panels/PDKPanelSetting.js",
	"bin-debug/views/panels/PDKPanelShare.js",
	"bin-debug/views/panels/PDKPanelSign.js",
	"bin-debug/views/panels/PDKPanelThanksgiving.js",
	"bin-debug/views/panels/PDKPanelWatchWX.js",
	"bin-debug/views/scenes/PDKSceneCommon.js",
	"bin-debug/views/scenes/PDKSceneEffect.js",
	"bin-debug/views/scenes/PDKSceneGameSel.js",
	"bin-debug/views/scenes/PDKSceneLoading.js",
	"bin-debug/views/scenes/PDKSceneLogin.js",
	"bin-debug/views/scenes/PDKSceneMostTop.js",
	"bin-debug/views/scenes/PDKSceneRoom.js",
	"bin-debug/PDKotherGameCfg.js",
	//----auto game_file_list end----
];

var window = {};

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "RunFastMain",
		frameRate: 18,
		scaleMode: "fixedHeight",
		contentWidth: 1280,
		contentHeight: 640,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:20,textColor:0x00d8ff,bgAlpha:0.6",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};