class LanguagePack{
	loading:string;
	config_url:string;
	debug:string;
	config_url_1:string;
	first_alert_title:string;
	first_alert_buttons:any[];
	service_provision_url:string;
	service_provision:string;
	health_game_advise:string;
	loginError:any;
	joinPGameErr:any;
	guessCardsNotice:any;
	createPGameErr:any;
	login_waiting:string;
	disconnect_kick_out:any;
	disconnect_server:string;
	auto_reconnect:string;
	waiting_for_getting_information:string;
	backAlert:string;
	backAlert1:string;
	roomLimit1:string;
	roomLimit2:string;
	roomAmount:string;
	quick_join_error:any;
	upload_avatar:string;
	no_more_desk:string;
	noMoreGold:string;
	noMoreGold2:string;
	noMoreGold3:string;
	browNoGold:string;
	reportSucc:string;
	repeatReport:string;
	gameResult:string;
	sex:any[];
	sexVoice:any[];
	people:string;
	second:string;
	gold:string;
	score:string;
	year:string;
	month:string;
	day:string;
	sky:string;
	format_y_m_d:string;
	format_m_d:string;
	currency:string;
	play_turn:string;
	no_ranking:string;
	confirm:string;
	reconnect:string;
	history:string;
	chatList:any[];
	free_pay:string;
	match_sign_up_result:any;
	match_jikai_limit:string;
	match_jikai_reward:string;
	match_title_reward_intro:string;
	match_title_match_intro:string;
	match_play_info:string;
	match_result_match_name:string;
	match_waiting_other_desk_1:string;
	match_waiting_other_desk_2:string;
	match_get_in:string;
	match_get_in2:string;
	match_result_praise:any[];
	match_cancel_alert:string;
	match_turn_name:any[];
	match_top_info_1:string;
	match_top_info_2:string;
	match_top_info_3:string;
	match_top_notify:string;
	match_notice_alert:string;
	modify_profile_success:string;
	modify_profile_failed:string;
	modify_profile_err:any;
	set_password_error:any;
	bank_operate:any[];
	bank_operate_error:any;
	bind_phone_notice:string;
	download_client_notice:string;
	alms_success:string;
	alms_success_continue:string;
	alms_success_exit:string;
	version_content:string;
	version_content_notice:any[];
	recharge_scale:string;
	recharge_addition:string;
	recharge_waiting:string;
	recharge_failed:string;
	recharge_cancel:string;
	recharge_success_simple:string;
	recharge_success:string;
	get_code_error:any;
	bind_phone_error:any;
	bind_third_part:any;
    exchange_redcoin: any;
    exchange_roomid: any;
	match_reward:any;
    exchange_redcoin_gold:string;
    exchange_redcoin_red:string;
    kickback_str: string;
    timeout: string;
    exchange_succ1:string;
    exchange_succ2: string;
    back_to_official:string;
    share_succ:string;
    win_cut:string;
    wx_service:string;
    ddz_gz:string;
    thirdPartWxMp:any;
    thirdPartQunHei:any;
    thirdPartHaiWanWan:any;
    thirdPartGame8868:any;
    thirdPartGame1905:any;
    thirdPartGameAiYouXi:any;
	dayTaskOne:any;
	dayTaskTwo:any;
	recordCardHour:any;
	recordCardDay:any;
	redCoin:any;
	taskNotExist:any;
	taskNotOver:any;
	taskHasGetRew:any;
	commonTopNotifyLable_1:any;
	commonTopNotifyLable_2:any;
}
class LanguageIds{
	loading:string = 'loading';
	config_url:string = 'config_url';
	config_url_1:string = 'config_url_1';
	first_alert_title:string = 'first_alert_title';
	first_alert_buttons:string = 'first_alert_buttons';
	service_provision_url:string = 'service_provision_url';
	service_provision:string = 'service_provision';
	health_game_advise:string = 'health_game_advise';
	loginError:string = 'loginError';
	login_waiting:string = 'login_waiting';
	disconnect_kick_out:string = 'disconnect_kick_out';
	disconnect_server:string = 'disconnect_server';
	auto_reconnect:string = 'auto_reconnect';
	waiting_for_getting_information:string = 'waiting_for_getting_information';
	backAlert:string = 'backAlert';
	roomLimit1:string = 'roomLimit1';
	roomLimit2:string = 'roomLimit2';
	roomAmount:string = 'roomAmount';
	quick_join_error:string = 'quick_join_error';
	upload_avatar:string = 'upload_avatar';
	no_more_desk:string = 'no_more_desk';
	noMoreGold:string = 'noMoreGold';
	noMoreGold2:string = 'noMoreGold2';
	noMoreGold3:string = 'noMoreGold3';
	browNoGold:string = 'browNoGold';
	reportSucc:string = 'reportSucc';
	repeatReport:string = 'repeatReport';
	gameResult:string = 'gameResult';
	sex:string = 'sex';
	sexVoice:string = 'sexVoice';
	people:string = 'people';
	second:string = 'second';
	gold:string = 'gold';
	score:string = 'score';
	year:string = 'year';
	month:string = 'month';
	day:string = 'day';
	sky:string = 'sky';
	format_y_m_d:string = 'format_y_m_d';
	format_m_d:string = 'format_m_d';
	currency:string = 'currency';
	play_turn:string = 'play_turn';
	no_ranking:string = 'no_ranking';
	confirm:string = 'confirm';
	reconnect:string = 'reconnect';
	history:string = 'history';
	chatList:string = 'chatList';
	free_pay:string = 'free_pay';
	match_sign_up_result:string = 'match_sign_up_result';
	match_jikai_limit:string = 'match_jikai_limit';
	match_jikai_reward:string = 'match_jikai_reward';
	match_title_reward_intro:string = 'match_title_reward_intro';
	match_title_match_intro:string = 'match_title_match_intro';
	match_play_info:string = 'match_play_info';
	match_result_match_name:string = 'match_result_match_name';
	match_waiting_other_desk_1:string = 'match_waiting_other_desk_1';
	match_waiting_other_desk_2:string = 'match_waiting_other_desk_2';
	match_get_in:string = 'match_get_in';
	match_get_in2:string = 'match_get_in2';
	match_result_praise:string = 'match_result_praise';
	match_cancel_alert:string = 'match_cancel_alert';
	match_turn_name:string = 'match_turn_name';
	match_top_info_1:string = 'match_top_info_1';
	match_top_info_2:string = 'match_top_info_2';
	match_top_info_3:string = 'match_top_info_3';
	match_top_notify:string = 'match_top_notify';
	match_notice_alert:string = 'match_notice_alert';
	modify_profile_success:string = 'modify_profile_success';
	modify_profile_failed:string = 'modify_profile_failed';
	modify_profile_err:string = 'modify_profile_err';
	set_password_error:string = 'set_password_error';
	bank_operate:string = 'bank_operate';
	bank_operate_error:string = 'bank_operate_error';
	bind_phone_notice:string = 'bind_phone_notice';
	download_client_notice:string = 'download_client_notice';
	alms_success:string = 'alms_success';
	alms_success_continue:string = 'alms_success_continue';
	alms_success_exit:string = 'alms_success_exit';
	version_content:string = 'version_content';
	version_content_notice:string = 'version_content_notice';
	recharge_scale:string = 'recharge_scale';
	recharge_addition:string = 'recharge_addition';
	recharge_waiting:string = 'recharge_waiting';
	recharge_failed:string = 'recharge_failed';
	recharge_cancel:string = 'recharge_cancel';
	recharge_success_simple:string = 'recharge_success_simple';
	recharge_success:string = 'recharge_success';
	get_code_error:string = 'get_code_error';
	bind_phone_error:string = 'bind_phone_error';
	bind_third_part:string = 'bind_third_part';
    exchange_redcoin: string = 'exchange_redcoin';
    exchange_roomid: string = 'exchange_roomid';
    kickback_str: string = 'kickback_str';
	dayTaskOne:string = 'dayTaskOne';
	dayTaskTwo:string = 'dayTaskTwo';
	recordCardHour:string ='recordCardHour';
	recordCardDay:string ='recordCardDay';
	redCoin:string = 'redCoin';
	taskNotExist:string = 'taskNotExist';
	taskNotOver:string = 'taskNotOver';
	taskHasGetRew:string = 'taskHasGetRew';
	commonTopNotifyLable_1:string = 'commonTopNotifyLable_1';
	commonTopNotifyLable_2:string = 'commonTopNotifyLable_2';
}